self.get_container(container_ptr).owned_procs =~= self.get_container(container_ptr).owned_procs,
self.get_container(container_ptr).parent =~= self.get_container(container_ptr).parent,
self.get_container(container_ptr).parent_rev_ptr =~= self.get_container(container_ptr).parent_rev_ptr,
self.get_container(container_ptr).children =~= self.get_container(container_ptr).children,
self.get_container(container_ptr).owned_endpoints =~= self.get_container(container_ptr).owned_endpoints,
// self.get_container(container_ptr).mem_quota =~= self.get_container(container_ptr).mem_quota,
self.get_container(container_ptr).mem_used =~= self.get_container(container_ptr).mem_used,
self.get_container(container_ptr).owned_cpus =~= self.get_container(container_ptr).owned_cpus,
self.get_container(container_ptr).scheduler =~= self.get_container(container_ptr).scheduler,
self.get_container(container_ptr).mem_quota =~= value,